### ISSUE TITLE
问题：前端在一条命令发送后无法继续发送

### ISSUE THREAD

**Issue by TXZdream** [sysu-go-online/front-end#11]
## 描述
例如，在输入apt update后，同一命令下的所有其他输入，均不会被传至后台

**Comment by kangbb** [comment]
对于终端输入，我考虑到的是：每次只允许同时运行一条命令，除非该条命令运行完毕，并关闭websocket连接。感觉这样更方便显示结果，不是吗？

**Comment by TXZdream** [comment]
你的理解可能有点问题，我的意思是交互式的命令，比如说，你写了一个程序，这个程序跑起来之后会要求接收一组输入，现在的问题是，前端运行一个命令后，在这个命令结束之前，所有的输入都不会被传输到后台，这个是问题所在，不知你理解了没？

**Comment by TXZdream** [comment]
已解决
