### ISSUE TITLE
问题：创建文件(夹)错误

### ISSUE THREAD

**Issue by TXZdream** [sysu-go-online/front-end#8]
## 重复方式
在任意文件夹下创建文件(夹)，会发现实际添加的文件是根目录下的undifined文件

**Comment by kangbb** [comment]
已经修复。
后端处理似乎存在问题：
1.无法处理增加删除文件请求。
2. 后端ws路由应该为 ‘api/ws'

**Comment by TXZdream** [comment]
前端已修复
